# backend/main.py
import os
import shutil
from typing import List, Literal, Optional

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FILES_DIR = os.path.join(BASE_DIR, "boardwalk_files")
os.makedirs(FILES_DIR, exist_ok=True)

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------- MODELS ----------

class AgentScope(BaseModel):
    project: str
    goal: str
    stack: str
    allow_scaffold: bool
    allow_db: bool
    allow_api: bool
    allow_auth: bool
    allow_media: bool
    allow_cloudflare: bool
    allow_frontend: bool
    allow_service_worker: bool
    allow_deploy: bool
    allow_fix: bool
    mode: Literal["full", "limited"]


class AgentEvent(BaseModel):
    kind: str
    message: str


class AgentRunResponse(BaseModel):
    events: List[AgentEvent]
    summary: str


class FixErrorsRequest(BaseModel):
    project: str
    errors: str


class FixErrorsResponse(BaseModel):
    events: List[AgentEvent]
    summary: str


# ---------- HELPERS ----------

def safe_name(name: str) -> str:
    return name.replace("..", "_").strip().replace(" ", "-")


def project_root(project: str) -> str:
    return os.path.join(FILES_DIR, safe_name(project))


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def write_file(path: str, content: str) -> None:
    ensure_dir(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ---------- SCAFFOLDERS ----------

def scaffold_fullstack(stack: str, project: str, events: List[AgentEvent]) -> None:
    root = project_root(project)
    if os.path.exists(root):
        shutil.rmtree(root)
    ensure_dir(root)

    write_file(
        os.path.join(root, "README.md"),
        f"# {project}\n\nGenerated by Boardwalk AI Autonomous Builder.\nGoal: {project}\n",
    )

    if stack == "react-node":
        backend_dir = os.path.join(root, "backend")
        frontend_dir = os.path.join(root, "frontend")
        ensure_dir(backend_dir)
        ensure_dir(frontend_dir)

        write_file(
            os.path.join(backend_dir, "package.json"),
            """{
  "name": "backend",
  "version": "1.0.0",
  "main": "server.js",
  "scripts": {
    "dev": "node server.js",
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.19.0",
    "cors": "^2.8.5"
  }
}
""",
        )
        write_file(
            os.path.join(backend_dir, "server.js"),
            """const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());

app.get("/api/health", (req, res) => {
  res.json({ ok: true, service: "backend", stack: "react-node" });
});

const port = process.env.PORT || 4000;
app.listen(port, () => {
  console.log("Backend listening on port", port);
});
""",
        )

        write_file(
            os.path.join(frontend_dir, "package.json"),
            """{
  "name": "frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0"
  }
}
""",
        )
        write_file(
            os.path.join(frontend_dir, "index.html"),
            """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>React Frontend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
""",
        )
        ensure_dir(os.path.join(frontend_dir, "src"))
        write_file(
            os.path.join(frontend_dir, "src", "main.jsx"),
            """import React from "react";
import ReactDOM from "react-dom/client";

function App() {
  return (
    <div style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>React + Node App</h1>
      <p>Generated by Boardwalk AI Autonomous Builder.</p>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
""",
        )
        events.append(AgentEvent(kind="agent", message="Scaffolded React + Node full stack."))

    elif stack == "react-fastapi":
        backend_dir = os.path.join(root, "backend")
        frontend_dir = os.path.join(root, "frontend")
        ensure_dir(backend_dir)
        ensure_dir(frontend_dir)

        write_file(
            os.path.join(backend_dir, "main.py"),
            """from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/health")
def health():
    return {"ok": True, "service": "backend", "stack": "react-fastapi"}
""",
        )
        write_file(
            os.path.join(backend_dir, "requirements.txt"),
            "fastapi\nuvicorn[standard]\n",
        )

        write_file(
            os.path.join(frontend_dir, "package.json"),
            """{
  "name": "frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0"
  }
}
""",
        )
        ensure_dir(os.path.join(frontend_dir, "src"))
        write_file(
            os.path.join(frontend_dir, "index.html"),
            """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>React + FastAPI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
""",
        )
        write_file(
            os.path.join(frontend_dir, "src", "main.jsx"),
            """import React from "react";
import ReactDOM from "react-dom/client";

function App() {
  return (
    <div style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>React + FastAPI App</h1>
      <p>Generated by Boardwalk AI Autonomous Builder.</p>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
""",
        )
        events.append(AgentEvent(kind="agent", message="Scaffolded React + FastAPI full stack."))

    elif stack == "svelte-worker":
        worker_dir = os.path.join(root, "backend-worker")
        frontend_dir = os.path.join(root, "frontend-svelte")
        ensure_dir(worker_dir)
        ensure_dir(frontend_dir)

        write_file(
            os.path.join(worker_dir, "worker.js"),
            """export default {
  async fetch(request, env, ctx) {
    return new Response("Hello from Cloudflare Worker backend (svelte-worker stack)", {
      status: 200,
      headers: { "content-type": "text/plain" }
    });
  }
};
""",
        )
        write_file(
            os.path.join(worker_dir, "wrangler.toml"),
            f"""name = "{safe_name(project)}-worker"
main = "worker.js"
compatibility_date = "2024-04-08"
""",
        )

        write_file(
            os.path.join(frontend_dir, "package.json"),
            """{
  "name": "frontend-svelte",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^3.0.0",
    "svelte": "^4.0.0",
    "vite": "^5.0.0"
  }
}
""",
        )
        ensure_dir(os.path.join(frontend_dir, "src"))
        write_file(
            os.path.join(frontend_dir, "index.html"),
            """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Svelte + Worker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
""",
        )
        write_file(
            os.path.join(frontend_dir, "src", "main.js"),
            """import App from "./App.svelte";

const app = new App({
  target: document.getElementById("app")
});

export default app;
""",
        )
        write_file(
            os.path.join(frontend_dir, "src", "App.svelte"),
            """<main style="padding:24px;font-family:system-ui;">
  <h1>Svelte + Cloudflare Worker</h1>
  <p>Generated by Boardwalk AI Autonomous Builder.</p>
</main>
""",
        )
        events.append(AgentEvent(kind="agent", message="Scaffolded Svelte + Cloudflare Worker full stack."))

    elif stack == "next-node":
        root_dir = project_root(project)
        app_dir = os.path.join(root_dir, "app")
        ensure_dir(app_dir)
        write_file(
            os.path.join(root_dir, "package.json"),
            """{
  "name": "next-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "18.0.0",
    "react-dom": "18.0.0"
  }
}
""",
        )
        write_file(
            os.path.join(app_dir, "page.jsx"),
            """export default function Page() {
  return (
    <main style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>Next.js + Node App</h1>
      <p>Generated by Boardwalk AI Autonomous Builder.</p>
    </main>
  );
}
""",
        )
        events.append(AgentEvent(kind="agent", message="Scaffolded Next.js app (frontend + built-in API routes ready)."))

    elif stack == "vanilla-html":
        root_dir = project_root(project)
        ensure_dir(root_dir)
        write_file(
            os.path.join(root_dir, "index.html"),
            """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Vanilla App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="manifest" href="/manifest.json" />
  </head>
  <body>
    <div id="app"></div>
    <script src="/app.js"></script>
  </body>
</html>
""",
        )
        write_file(
            os.path.join(root_dir, "app.js"),
            """document.getElementById("app").innerHTML = `
  <main style="padding:24px;font-family:system-ui;">
    <h1>Vanilla HTML/CSS/JS App</h1>
    <p>Generated by Boardwalk AI Autonomous Builder.</p>
  </main>
`;
""",
        )
        events.append(AgentEvent(kind="agent", message="Scaffolded vanilla HTML/CSS/JS app."))
    else:
        events.append(AgentEvent(kind="error", message=f"Unknown stack '{stack}'"))


# ---------- DB / MIGRATIONS ----------

def create_db_layer(project: str, events: List[AgentEvent]) -> None:
    db_dir = os.path.join(project_root(project), "db")
    ensure_dir(db_dir)
    write_file(
        os.path.join(db_dir, "schema.sql"),
        """-- Example schema; extend as needed
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  token TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);
""",
    )
    write_file(
        os.path.join(db_dir, "migrations.md"),
        "# Migrations\n\n- 0001_initial_users_sessions\n",
    )
    events.append(AgentEvent(kind="agent", message="Database schema and migrations stub created."))


# ---------- API BACKEND ----------

def create_api_layer(project: str, events: List[AgentEvent]) -> None:
    backend_dir = os.path.join(project_root(project), "backend")
    ensure_dir(backend_dir)
    write_file(
        os.path.join(backend_dir, "api_spec.md"),
        f"""# API Spec for {project}

- GET /api/health
- POST /api/login
- POST /api/register
- GET /api/me
""",
    )
    write_file(
        os.path.join(backend_dir, "server.js"),
        """const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());

// Health
app.get("/api/health", (req, res) => {
  res.json({ ok: true, service: "api" });
});

// TODO: Implement /api/login, /api/register, /api/me

const port = process.env.PORT || 4000;
app.listen(port, () => {
  console.log("API backend listening on port", port);
});
""",
    )
    events.append(AgentEvent(kind="agent", message="API backend skeleton created (Express)."))


# ---------- AUTH LAYER ----------

def create_auth_layer(project: str, events: List[AgentEvent]) -> None:
    backend_dir = os.path.join(project_root(project), "backend")
    ensure_dir(backend_dir)
    write_file(
        os.path.join(backend_dir, "auth.js"),
        """// Basic auth helpers (to be wired into routes)
const crypto = require("crypto");

function hashPassword(password) {
  return crypto.createHash("sha256").update(password).digest("hex");
}

function generateToken() {
  return crypto.randomBytes(32).toString("hex");
}

module.exports = { hashPassword, generateToken };
""",
    )
    events.append(AgentEvent(kind="agent", message="Auth helper module created (hashing + token generation)."))


# ---------- MEDIA / R2 ----------

def create_media_layer(project: str, events: List[AgentEvent]) -> None:
    cf_dir = os.path.join(project_root(project), "cloudflare")
    ensure_dir(cf_dir)
    bucket_name = f"{safe_name(project)}-media"
    write_file(
        os.path.join(cf_dir, "r2.toml"),
        f"""[[r2_buckets]]
binding = "{bucket_name}"
bucket_name = "{bucket_name}"
preview_bucket_name = "{bucket_name}-preview"
""",
    )
    backend_dir = os.path.join(project_root(project), "backend")
    ensure_dir(backend_dir)
    write_file(
        os.path.join(backend_dir, "media.md"),
        f"""# Media Pipeline

- R2 bucket: {bucket_name}
- Use signed URLs for uploads/downloads.
- Wire this into your Worker or backend API.
""",
    )
    events.append(AgentEvent(kind="agent", message="Cloudflare R2 config and media notes created."))


# ---------- CLOUDFLARE (KV, D1, QUEUES, CRON) ----------

def create_cloudflare_layer(project: str, events: List[AgentEvent]) -> None:
    cf_dir = os.path.join(project_root(project), "cloudflare")
    ensure_dir(cf_dir)
    write_file(
        os.path.join(cf_dir, "wrangler.toml"),
        f"""name = "{safe_name(project)}-worker"
main = "worker.js"
compatibility_date = "2024-04-08"

[[kv_namespaces]]
binding = "{safe_name(project).upper()}_KV"
id = "00000000000000000000000000000000"

[[d1_databases]]
binding = "{safe_name(project).upper()}_D1"
database_name = "{safe_name(project)}-db"
database_id = "00000000-0000-0000-0000-000000000000"

[[queues.producers]]
binding = "{safe_name(project).upper()}_QUEUE"
queue = "{safe_name(project)}-queue"

[triggers]
crons = ["0 * * * *"]
""",
    )
    write_file(
        os.path.join(cf_dir, "worker.js"),
        """export default {
  async fetch(request, env, ctx) {
    return new Response("Cloudflare Worker for app", {
      status: 200,
      headers: { "content-type": "text/plain" }
    });
  },

  async queue(batch, env, ctx) {
    for (const msg of batch.messages) {
      console.log("Queue message", msg.body);
    }
  },

  async scheduled(event, env, ctx) {
    console.log("Cron trigger", event.cron);
  }
};
""",
    )
    events.append(AgentEvent(kind="agent", message="Cloudflare Worker + KV + D1 + Queue + Cron config created."))


# ---------- FRONTEND / PWA ----------

def create_frontend_layer(project: str, events: List[AgentEvent]) -> None:
    root = project_root(project)
    write_file(
        os.path.join(root, "manifest.json"),
        f"""{{
  "name": "{project}",
  "short_name": "{project}",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#05060a",
  "theme_color": "#05060a",
  "icons": []
}}
""",
    )
    write_file(
        os.path.join(root, "service-worker.js"),
        """self.addEventListener("install", (event) => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  clients.claim();
});

self.addEventListener("fetch", (event) => {
  // Extend with caching if needed
});
""",
    )
    events.append(AgentEvent(kind="agent", message="PWA manifest and service worker created."))


# ---------- DEPLOYMENT CONFIGS ----------

def create_deploy_layer(project: str, events: List[AgentEvent]) -> None:
    root = project_root(project)
    write_file(
        os.path.join(root, "Dockerfile"),
        """# Example Dockerfile; adjust to your stack
FROM node:20-alpine
WORKDIR /app
COPY . .
RUN npm install || true
CMD ["npm", "run", "dev"]
""",
    )
    write_file(
        os.path.join(root, "deploy.md"),
        """# Deployment Notes

- Use Dockerfile for container-based deployment.
- Use cloudflare/wrangler.toml for Worker deployment.
- Configure environment variables for secrets.
""",
    )
    events.append(AgentEvent(kind="agent", message="Deployment notes and Dockerfile created."))


# ---------- ERROR ANALYSIS / AUTO-FIX ----------

def analyze_and_fix_errors(project: str, errors: str, events: List[AgentEvent]) -> None:
    root = project_root(project)
    ensure_dir(root)
    write_file(
        os.path.join(root, "diagnostics.log"),
        errors,
    )
    write_file(
        os.path.join(root, "diagnostics.md"),
        f"# Diagnostics for {project}\n\n```\n{errors}\n```\n\nNext steps:\n- Inspect diagnostics.log\n- Adjust code or configs accordingly.\n",
    )
    events.append(AgentEvent(kind="agent", message="Error log captured to diagnostics.log and diagnostics.md for this project."))


# ---------- AGENT LOOP ----------

def run_agent(scope: AgentScope) -> AgentRunResponse:
    events: List[AgentEvent] = []
    events.append(AgentEvent(kind="system", message=f"Agent started in {scope.mode} mode for project '{scope.project}'."))

    if scope.allow_scaffold:
        scaffold_fullstack(scope.stack, scope.project, events)

    if scope.allow_db:
        create_db_layer(scope.project, events)

    if scope.allow_api:
        create_api_layer(scope.project, events)

    if scope.allow_auth:
        create_auth_layer(scope.project, events)

    if scope.allow_media:
        create_media_layer(scope.project, events)

    if scope.allow_cloudflare:
        create_cloudflare_layer(scope.project, events)

    if scope.allow_frontend or scope.allow_service_worker:
        create_frontend_layer(scope.project, events)

    if scope.allow_deploy:
        create_deploy_layer(scope.project, events)

    summary = f"Agent completed for project '{scope.project}' with stack '{scope.stack}'."
    events.append(AgentEvent(kind="system", message=summary))
    return AgentRunResponse(events=events, summary=summary)


# ---------- ENDPOINTS ----------

@app.post("/api/agent/run", response_model=AgentRunResponse)
def api_agent_run(scope: AgentScope):
    return run_agent(scope)


@app.post("/api/agent/fix_errors", response_model=FixErrorsResponse)
def api_fix_errors(req: FixErrorsRequest):
    events: List[AgentEvent] = []
    events.append(AgentEvent(kind="system", message=f"Received error log for project '{req.project}'."))
    analyze_and_fix_errors(req.project, req.errors, events)
    summary = f"Diagnostics written for project '{req.project}'."
    events.append(AgentEvent(kind="system", message=summary))
    return FixErrorsResponse(events=events, summary=summary)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
